import { contactPageContent } from "@/content/contactPage";
import { publisher } from "@/content/legal/identity";

// Site-level SEO constants + the business NAP in structured form. Single home of the
// global defaults (Pierre's decision: code-level defaults, no `siteSettings` singleton —
// see ADR 0025). The FLAT display strings stay in `@/content/legal/identity.ts` (éditeur)
// and `@/content/contactPage.ts` (geo); this module derives the SEO/structured-data shapes
// from them so there is a single source for the raw values.

/**
 * Canonical site origin — server-resolved, no trailing slash. Prefer a non-`NEXT_PUBLIC_`
 * `SITE_URL` (Coolify runtime var — the CLAUDE.md prefix rule: server-injected values must
 * not be inlined at build), fall back to the existing `NEXT_PUBLIC_SITE_URL` (already read
 * by robots/sitemap) then the prod domain. This is THE single source for the origin — robots
 * and sitemap import it too.
 */
export const SITE_URL = (
	process.env.SITE_URL ??
	process.env.NEXT_PUBLIC_SITE_URL ??
	"https://estuaire.fr"
).replace(/\/+$/, "");

/** Public brand name (what appears in tabs / social cards / titles). */
export const SITE_NAME = "Estuaire";

/** Open Graph locale. */
export const SITE_LOCALE = "fr_FR";

/**
 * Global default meta/share description — the fallback when a page (or the CMS) provides
 * none. Kept concise (≈150 chars) and aligned with the brand positioning.
 */
export const DEFAULT_DESCRIPTION =
	"Estuaire, par Mosaique Production : agenceur-concepteur d'agencement, mobilier et présentoirs sur mesure. De l'analyse à l'installation, conçus et fabriqués dans notre atelier.";

/** The logomark served by the `app/icon.svg` metadata file — usable as the Organization logo. */
export const LOGO_PATH = "/icon.svg";

/**
 * Default Open Graph / Twitter share image — the branded image generated by
 * `app/opengraph-image.tsx`, served at `/opengraph-image`. Referenced EXPLICITLY by
 * `buildMetadata` (not left to Next's file auto-injection, which is dropped once a page sets
 * its own `openGraph`). `url` is site-root-relative → resolved to absolute via `metadataBase`.
 * Dimensions are fixed by the generator.
 */
export const DEFAULT_OG_IMAGE = {
	url: "/opengraph-image",
	alt: `${SITE_NAME} : agencement, mobilier et présentoirs sur mesure`,
	width: 1200,
	height: 630,
} as const;

/**
 * Organization / LocalBusiness social profiles (`sameAs`) — the canonical profiles Google uses
 * to consolidate the entity / knowledge panel. LinkedIn is the only official profile (Pierre,
 * 2026-07-06). Builders omit `sameAs` when this is empty.
 */
export const SAME_AS: string[] = [
	"https://www.linkedin.com/company/estuaire-agencement/",
];

/**
 * Structured postal address (schema.org `PostalAddress`). Derived from the flat
 * `publisher.address` string (kept as the human display source). Machecoul-Saint-Même is the
 * commune (the atelier / registered seat), Loire-Atlantique, Pays de la Loire.
 */
export const POSTAL_ADDRESS = {
	streetAddress: "ZI La Seiglerie 3, 2 rue Henri Giffard",
	postalCode: "44270",
	addressLocality: "Machecoul-Saint-Même",
	addressRegion: "Pays de la Loire",
	addressCountry: "FR",
} as const;

/** Geo coordinates of the atelier (single source: the contact-page maquette content). */
export const GEO = {
	latitude: contactPageContent.mapLocation.lat,
	longitude: contactPageContent.mapLocation.lng,
} as const;

/** Phone in E.164 form (schema.org `telephone`), derived from `publisher.phone`. */
export const TELEPHONE_E164 = "+33285526202";

/** Raw business identity re-exported for the structured-data builders (single source). */
export const BUSINESS = {
	legalName: publisher.legalName,
	brand: publisher.brand,
	email: publisher.email,
	vatID: publisher.vat,
	siret: publisher.siret,
} as const;

/** Build a site-absolute URL from a root-relative path (idempotent on absolute URLs). */
export function absoluteUrl(path = "/"): string {
	if (/^https?:\/\//.test(path)) return path;
	return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}
