/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ctaTitleOutline?: string;
  ctaTitleFill?: string;
  ctaButtonLabel?: string;
  ctaButtonHref?: string;
  ctaImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tagline?: string;
  address?: string;
  contactHref?: string;
  linkedInUrl?: string;
  plaquetteLabel?: string;
  plaquetteFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  navLinks?: Array<{
    label?: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
  legalLinks?: Array<{
    label?: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = Footer | SanityImageCrop | SanityImageHotspot | HomePage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    title,    tagline  }
export type HOME_PAGE_QUERYResult = {
  title: string | null;
  tagline: null;
} | {
  title: null;
  tagline: string | null;
} | {
  title: string | null;
  tagline: string | null;
} | null;
// Variable: FOOTER_QUERY
// Query: *[_id == "footer"][0]{    ctaTitleOutline,    ctaTitleFill,    ctaButtonLabel,    ctaButtonHref,    ctaImages[]{      asset,      hotspot,      crop,      alt,      "lqip": asset->metadata.lqip    },    tagline,    address,    contactHref,    linkedInUrl,    plaquetteLabel,    "plaquetteUrl": plaquetteFile.asset->url,    navLinks[]{ label, href },    legalLinks[]{ label, href }  }
export type FOOTER_QUERYResult = {
  ctaTitleOutline: null;
  ctaTitleFill: null;
  ctaButtonLabel: null;
  ctaButtonHref: null;
  ctaImages: null;
  tagline: null;
  address: null;
  contactHref: null;
  linkedInUrl: null;
  plaquetteLabel: null;
  plaquetteUrl: null;
  navLinks: null;
  legalLinks: null;
} | {
  ctaTitleOutline: null;
  ctaTitleFill: null;
  ctaButtonLabel: null;
  ctaButtonHref: null;
  ctaImages: null;
  tagline: string | null;
  address: null;
  contactHref: null;
  linkedInUrl: null;
  plaquetteLabel: null;
  plaquetteUrl: null;
  navLinks: null;
  legalLinks: null;
} | {
  ctaTitleOutline: string | null;
  ctaTitleFill: string | null;
  ctaButtonLabel: string | null;
  ctaButtonHref: string | null;
  ctaImages: Array<{
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
  }> | null;
  tagline: string | null;
  address: string | null;
  contactHref: string | null;
  linkedInUrl: string | null;
  plaquetteLabel: string | null;
  plaquetteUrl: string | null;
  navLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  legalLinks: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_id == \"homePage\"][0]{\n    title,\n    tagline\n  }\n": HOME_PAGE_QUERYResult;
    "\n  *[_id == \"footer\"][0]{\n    ctaTitleOutline,\n    ctaTitleFill,\n    ctaButtonLabel,\n    ctaButtonHref,\n    ctaImages[]{\n      asset,\n      hotspot,\n      crop,\n      alt,\n      \"lqip\": asset->metadata.lqip\n    },\n    tagline,\n    address,\n    contactHref,\n    linkedInUrl,\n    plaquetteLabel,\n    \"plaquetteUrl\": plaquetteFile.asset->url,\n    navLinks[]{ label, href },\n    legalLinks[]{ label, href }\n  }\n": FOOTER_QUERYResult;
  }
}
