/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ctaTitleOutline?: string;
  ctaTitleFill?: string;
  ctaButtonLabel?: string;
  ctaButtonHref?: string;
  ctaImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  tagline?: string;
  address?: string;
  contactHref?: string;
  linkedInUrl?: string;
  plaquetteLabel?: string;
  plaquetteFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  navLinks?: Array<{
    label?: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
  legalLinks?: Array<{
    label?: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroLabel?: string;
  heroSlides?: Array<{
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    titleOutline?: string;
    titleFill?: string;
    _type: "heroSlide";
    _key: string;
  }>;
  introTitleOutline?: string;
  introTitleFill?: string;
  introText?: string;
  introImagePrimary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introImageSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertisesTitleOutline?: string;
  expertisesTitleFill?: string;
  expertisesText?: string;
  expertisesImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertisesCtaLabel?: string;
  expertisesCtaHref?: string;
  universSectors?: Array<{
    label?: string;
    href?: string;
    _type: "sector";
    _key: string;
  }>;
  realisationsTitleOutline?: string;
  realisationsTitleFill?: string;
  realisationsCtaLabel?: string;
  realisationsCtaHref?: string;
  visionTitleOutline?: string;
  visionTitleFill?: string;
  visionText?: string;
  visionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  visionCtaLabel?: string;
  visionCtaHref?: string;
  seoMetaTitle?: string;
  seoMetaDescription?: string;
  seoOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Footer
  | SanityImageCrop
  | SanityImageHotspot
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/lib/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    heroLabel,    heroSlides[]{      titleOutline,      titleFill,      image{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip }    },    introTitleOutline,    introTitleFill,    introText,    introImagePrimary{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },    introImageSecondary{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },    expertisesTitleOutline,    expertisesTitleFill,    expertisesText,    expertisesImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },    expertisesCtaLabel,    expertisesCtaHref,    universSectors[]{ label, href },    realisationsTitleOutline,    realisationsTitleFill,    realisationsCtaLabel,    realisationsCtaHref,    visionTitleOutline,    visionTitleFill,    visionText,    visionImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },    visionCtaLabel,    visionCtaHref,    seoMetaTitle,    seoMetaDescription,    seoOgImage{ asset, alt }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      heroLabel: null;
      heroSlides: null;
      introTitleOutline: null;
      introTitleFill: null;
      introText: null;
      introImagePrimary: null;
      introImageSecondary: null;
      expertisesTitleOutline: null;
      expertisesTitleFill: null;
      expertisesText: null;
      expertisesImage: null;
      expertisesCtaLabel: null;
      expertisesCtaHref: null;
      universSectors: null;
      realisationsTitleOutline: null;
      realisationsTitleFill: null;
      realisationsCtaLabel: null;
      realisationsCtaHref: null;
      visionTitleOutline: null;
      visionTitleFill: null;
      visionText: null;
      visionImage: null;
      visionCtaLabel: null;
      visionCtaHref: null;
      seoMetaTitle: null;
      seoMetaDescription: null;
      seoOgImage: null;
    }
  | {
      heroLabel: string | null;
      heroSlides: Array<{
        titleOutline: string | null;
        titleFill: string | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          lqip: string | null;
        } | null;
      }> | null;
      introTitleOutline: string | null;
      introTitleFill: string | null;
      introText: string | null;
      introImagePrimary: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      } | null;
      introImageSecondary: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      } | null;
      expertisesTitleOutline: string | null;
      expertisesTitleFill: string | null;
      expertisesText: string | null;
      expertisesImage: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      } | null;
      expertisesCtaLabel: string | null;
      expertisesCtaHref: string | null;
      universSectors: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      realisationsTitleOutline: string | null;
      realisationsTitleFill: string | null;
      realisationsCtaLabel: string | null;
      realisationsCtaHref: string | null;
      visionTitleOutline: string | null;
      visionTitleFill: string | null;
      visionText: string | null;
      visionImage: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      } | null;
      visionCtaLabel: string | null;
      visionCtaHref: string | null;
      seoMetaTitle: string | null;
      seoMetaDescription: string | null;
      seoOgImage: {
        asset: SanityImageAssetReference | null;
        alt: string | null;
      } | null;
    }
  | null;

// Source: src/lib/sanity/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_id == "footer"][0]{    ctaTitleOutline,    ctaTitleFill,    ctaButtonLabel,    ctaButtonHref,    ctaImages[]{      asset,      hotspot,      crop,      alt,      "lqip": asset->metadata.lqip    },    tagline,    address,    contactHref,    linkedInUrl,    plaquetteLabel,    "plaquetteUrl": plaquetteFile.asset->url,    navLinks[]{ label, href },    legalLinks[]{ label, href }  }
export type FOOTER_QUERY_RESULT =
  | {
      ctaTitleOutline: null;
      ctaTitleFill: null;
      ctaButtonLabel: null;
      ctaButtonHref: null;
      ctaImages: null;
      tagline: null;
      address: null;
      contactHref: null;
      linkedInUrl: null;
      plaquetteLabel: null;
      plaquetteUrl: null;
      navLinks: null;
      legalLinks: null;
    }
  | {
      ctaTitleOutline: string | null;
      ctaTitleFill: string | null;
      ctaButtonLabel: string | null;
      ctaButtonHref: string | null;
      ctaImages: Array<{
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
      }> | null;
      tagline: string | null;
      address: string | null;
      contactHref: string | null;
      linkedInUrl: string | null;
      plaquetteLabel: string | null;
      plaquetteUrl: string | null;
      navLinks: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      legalLinks: Array<{
        label: string | null;
        href: string | null;
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "homePage"][0]{\n    heroLabel,\n    heroSlides[]{\n      titleOutline,\n      titleFill,\n      image{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip }\n    },\n    introTitleOutline,\n    introTitleFill,\n    introText,\n    introImagePrimary{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },\n    introImageSecondary{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },\n    expertisesTitleOutline,\n    expertisesTitleFill,\n    expertisesText,\n    expertisesImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },\n    expertisesCtaLabel,\n    expertisesCtaHref,\n    universSectors[]{ label, href },\n    realisationsTitleOutline,\n    realisationsTitleFill,\n    realisationsCtaLabel,\n    realisationsCtaHref,\n    visionTitleOutline,\n    visionTitleFill,\n    visionText,\n    visionImage{ asset, hotspot, crop, alt, "lqip": asset->metadata.lqip },\n    visionCtaLabel,\n    visionCtaHref,\n    seoMetaTitle,\n    seoMetaDescription,\n    seoOgImage{ asset, alt }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "footer"][0]{\n    ctaTitleOutline,\n    ctaTitleFill,\n    ctaButtonLabel,\n    ctaButtonHref,\n    ctaImages[]{\n      asset,\n      hotspot,\n      crop,\n      alt,\n      "lqip": asset->metadata.lqip\n    },\n    tagline,\n    address,\n    contactHref,\n    linkedInUrl,\n    plaquetteLabel,\n    "plaquetteUrl": plaquetteFile.asset->url,\n    navLinks[]{ label, href },\n    legalLinks[]{ label, href }\n  }\n': FOOTER_QUERY_RESULT;
  }
}
